const  data =[
    { code: "DZ", country: "Algeria", region: "Africa" },
    { code: "AO", country: "Angola", region: "Africa" },
    { code: "BJ", country: "Benin", region: "Africa" },
    { code: "BW", country: "Botswana", region: "Africa" },
    { code: "BF", country: "Burkina Faso", region: "Africa" },
    { code: "BI", country: "Burundi", region: "Africa" },
    { code: "CV", country: "Cabo Verde", region: "Africa" },
    { code: "CM", country: "Cameroon", region: "Africa" },
    { code: "CF", country: "Central African Republic (the)", region: "Africa" },
    { code: "TD", country: "Chad", region: "Africa" },
    { code: "KM", country: "Comoros (the)", region: "Africa" },
    { code: "CD", country: "Congo (the Democratic Republic of the)", region: "Africa" },
    { code: "CG", country: "Congo (the)", region: "Africa" },
    { code: "CI", country: "Côte d'Ivoire", region: "Africa" },
    { code: "DJ", country: "Djibouti", region: "Africa" },
    { code: "EG", country: "Egypt", region: "Africa" },
    { code: "GQ", country: "Equatorial Guinea", region: "Africa" },
    { code: "ER", country: "Eritrea", region: "Africa" },
    { code: "SZ", country: "Eswatini", region: "Africa" },
    { code: "ET", country: "Ethiopia", region: "Africa" },
    { code: "GA", country: "Gabon", region: "Africa" },
    { code: "GM", country: "Gambia (the)", region: "Africa" },
    { code: "GH", country: "Ghana", region: "Africa" },
    { code: "GN", country: "Guinea", region: "Africa" },
    { code: "GW", country: "Guinea-Bissau", region: "Africa" },
    { code: "KE", country: "Kenya", region: "Africa" },
    { code: "LS", country: "Lesotho", region: "Africa" },
    { code: "LR", country: "Liberia", region: "Africa" },
    { code: "LY", country: "Libya", region: "Africa" },
    { code: "MG", country: "Madagascar", region: "Africa" },
    { code: "MW", country: "Malawi", region: "Africa" },
    { code: "ML", country: "Mali", region: "Africa" },
    { code: "MR", country: "Mauritania", region: "Africa" },
    { code: "MU", country: "Mauritius", region: "Africa" },
    { code: "YT", country: "Mayotte", region: "Africa" },
    { code: "MA", country: "Morocco", region: "Africa" },
    { code: "MZ", country: "Mozambique", region: "Africa" },
    { code: "NA", country: "Namibia", region: "Africa" },
    { code: "NE", country: "Niger (the)", region: "Africa" },
    { code: "NG", country: "Nigeria", region: "Africa" },
    { code: "RE", country: "Réunion", region: "Africa" },
    { code: "RW", country: "Rwanda", region: "Africa" },
    { code: "SH", country: "Saint Helena, Ascension and Tristan da Cunha", region: "Africa" },
    { code: "ST", country: "Sao Tome and Principe", region: "Africa" },
    { code: "SN", country: "Senegal", region: "Africa" },
    { code: "SC", country: "Seychelles", region: "Africa" },
    { code: "SL", country: "Sierra Leone", region: "Africa" },
    { code: "SO", country: "Somalia", region: "Africa" },
    { code: "ZA", country: "South Africa", region: "Africa" },
    { code: "SS", country: "South Sudan", region: "Africa" },
    { code: "SD", country: "Sudan (the)", region: "Africa" },
    { code: "TZ", country: "Tanzania, the United Republic of", region: "Africa" },
    { code: "TG", country: "Togo", region: "Africa" },
    { code: "TN", country: "Tunisia", region: "Africa" },
    { code: "UG", country: "Uganda", region: "Africa" },
    { code: "EH", country: "Western Sahara*", region: "Africa" },
    { code: "ZM", country: "Zambia", region: "Africa" },
    { code: "ZW", country: "Zimbabwe", region: "Africa" },
    { code: "AQ", country: "Antarctica", region: "Antarctic" },
    { code: "BV", country: "Bouvet Island", region: "Antarctic" },
    { code: "TF", country: "French Southern Territories (the)", region: "Antarctic" },
    { code: "HM", country: "Heard Island and McDonald Islands", region: "Antarctic" },
    { code: "GS", country: "South Georgia and the South Sandwich Islands", region: "Antarctic" },
    { code: "AF", country: "Afghanistan", region: "Asia" },
    { code: "AM", country: "Armenia", region: "Asia" },
    { code: "AZ", country: "Azerbaijan", region: "Asia" },
    { code: "BD", country: "Bangladesh", region: "Asia" },
    { code: "BT", country: "Bhutan", region: "Asia" },
    { code: "IO", country: "British Indian Ocean Territory (the)", region: "Asia" },
    { code: "BN", country: "Brunei Darussalam", region: "Asia" },
    { code: "KH", country: "Cambodia", region: "Asia" },
    { code: "CN", country: "China", region: "Asia" },
    { code: "GE", country: "Georgia", region: "Asia" },
    { code: "HK", country: "Hong Kong", region: "Asia" },
    { code: "IN", country: "India", region: "Asia" },
    { code: "ID", country: "Indonesia", region: "Asia" },
    { code: "JP", country: "Japan", region: "Asia" },
    { code: "KZ", country: "Kazakhstan", region: "Asia" },
    { code: "KP", country: "Korea (the Democratic People's Republic of)", region: "Asia" },
    { code: "KR", country: "Korea (the Republic of)", region: "Asia" },
    { code: "KG", country: "Kyrgyzstan", region: "Asia" },
    { code: "LA", country: "Lao People's Democratic Republic (the)", region: "Asia" },
    { code: "MO", country: "Macao", region: "Asia" },
    { code: "MY", country: "Malaysia", region: "Asia" },
    { code: "MV", country: "Maldives", region: "Asia" },
    { code: "MN", country: "Mongolia", region: "Asia" },
    { code: "MM", country: "Myanmar", region: "Asia" },
    { code: "NP", country: "Nepal", region: "Asia" },
    { code: "PK", country: "Pakistan", region: "Asia" },
    { code: "PH", country: "Philippines (the)", region: "Asia" },
    { code: "SG", country: "Singapore", region: "Asia" },
    { code: "LK", country: "Sri Lanka", region: "Asia" },
    { code: "TW", country: "Taiwan (Province of China)", region: "Asia" },
    { code: "TJ", country: "Tajikistan", region: "Asia" },
    { code: "TH", country: "Thailand", region: "Asia" },
    { code: "TL", country: "Timor-Leste", region: "Asia" },
    { code: "TM", country: "Turkmenistan", region: "Asia" },
    { code: "UZ", country: "Uzbekistan", region: "Asia" },
    { code: "VN", country: "Viet Nam", region: "Asia" },
    { code: "BZ", country: "Belize", region: "Central America" }
];
export default  data;